### ISSUE TITLE
Int vs long

### ISSUE THREAD

**Issue by KevinTwist** [MicrosoftDocs/cpp-docs.cs-cz#6]
Hi,
I was reading https://docs.microsoft.com/cs-cz/cpp/cpp/integer-limits?view=vs-2019 and int as well as long appear to have same min and max values.
Is that an error or am I just not getting something?
Thanks.

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 262486b8-5d80-2c0b-f2eb-40c86aaf6a61
* Version Independent ID: 26b45954-2bcc-263f-7522-0c72941141bb
* Content: [Omezení typu Integer](https://docs.microsoft.com/cs-cz/cpp/cpp/integer-limits?view=vs-2019#feedback)
* Content Source: [docs/cpp/integer-limits.md](https://github.com/MicrosoftDocs/cpp-docs.cs-cz/blob/live/docs/cpp/integer-limits.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @KevinTwist
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @KevinTwist

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/cpp-docs/issues/1756

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
